Exporter enhancement2
s0nik42/lotus-farcaster pull request #32
Opened 2021-09-05 05:33 UTC by clinta

This is a significant refactor of the farcaster exporter.

I started with the goal of adding features to serve the metrics directly over http, rather than relying on the prometheus node exporter. This was challenging because of the global state and calls to terminate that caused the entire program to exit.

This refactor removes all global variables, implements separate daemon and miner subclasses of the lotus class, and uses context and `with as` statements to handle writing out the final metrics for collection time and success status.

As for features this adds several. First of all farcaster will now use the same environment variables that lotus does `FULLNODE_API_INFO` and `MINER_API_INFO` to discover the urls and tokens. Falling back to looking for the files in `LOTUS_PATH` and `LOTUS_MINER_PATH`. Command line arguments are also supported which take priority.

Farcaster can now write to a file directly without relying on redirection in a cron job, using the `--file` option. And the feature I originally set out to build, farcaster can now listen on a TCP port and serve metrics directly to prometheus for scraping. It also supports sytemd socket activation so that farcaster can automatically be started when prometheus tries to scrape it. Sample service and socket unit files have been added.

These changes should be backwards compatible and not anything about the metrics exported.

2021-09-06 13:48 UTC, s0nik42 commented
Hi @clinta thank you very much for your PR !  let me look and it during the week.

2021-11-17 23:28 UTC, Breigner01 requested changes
You've done a really good job overall, there are just some changes to follow the standard coding style.
I've also seen that you've removed all the try except on requests on api but I think that they should stay since it can fail and it should be handled properly.
We're now waiting for @s0nik42 to review the parts I asked him to.

2021-11-17 23:28 UTC, Breigner01 commented on lotus-exporter-farcaster/lotus-exporter-farcaster.py
> +    except Exception as exp:
Do not except bare Exception it is too broad

2021-11-17 23:28 UTC, Breigner01 commented on lotus-exporter-farcaster/lotus-exporter-farcaster.py
> +    except Exception:
Do not except bare Exception

2021-11-17 23:28 UTC, Breigner01 commented on lotus-exporter-farcaster/lotus-exporter-farcaster.py
> +            except Exception:
Do not except bare Exception

2021-11-17 23:28 UTC, Breigner01 commented on lotus-exporter-farcaster/lotus-exporter-farcaster.py
> +        except Exception  as exp:
Do not except bare Exception

2021-11-17 23:28 UTC, Breigner01 commented on lotus-exporter-farcaster/lotus-exporter-farcaster.py
> +            raise DaemonError from exp
Should change according to new name

2021-11-17 23:28 UTC, Breigner01 commented on lotus-exporter-farcaster/lotus-exporter-farcaster.py
> +        except Exception  as exp:
Do not except bare Exception

2021-11-17 23:28 UTC, Breigner01 commented on lotus-exporter-farcaster/lotus-exporter-farcaster.py
> +            raise MinerError from exp
Should change according to new name

2021-11-22 21:55 UTC, merged